name: my-bookshop-mta
resources:
  containers:
  - container: mbt
    image: 'devxci/mbtci:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged

trigger:
- master

stages:
- stage: build
  displayName: Build MTA for SAP Cloud Platform using Cloud MTBuild Tool
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mbt
      steps:
        - bash: 'mbt build -p=cf'
        - publish: $(System.DefaultWorkingDirectory)/mta_archives/.
          artifact: mtar

- stage: deploy
  displayName: Deployment to SAP Cloud Platform (cf)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: mtar
        - bash: cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)"
          displayName: Login to SAP Cloud Platform
        - bash: cf deploy $(Pipeline.Workspace)/mtar/my-bookshop2_1.0.0.mtar -f
          displayName: Deploy mtar file
